### ISSUE TITLE
vitals uses significant power

### ISSUE THREAD

**Issue by garyemerson** [hmarr/vitals#17]
Pretty much the title. Somewhat concerning since I always have vitals running so being a bit power hungry could have a nontrivial effect on battery life.

I wonder if this is because vitals now tracks 3 or 4 different resources instead of just CPU. I'd be willing to look into creating a setting to toggle the resources a user wants to track which might allow users to mitigate this. Lmk if that sounds like a pull request you think you'd accept.

### Environment

- Vitals version 0.7
- Device: MacBook Air (Retina, 13-inch, 2018)
- OS version: macOS Monterey 12.0.1 (21A559)

### Images

<img width="1085" alt="Screen Shot 2022-01-16 at 7 38 35 PM" src="https://user-images.githubusercontent.com/5726308/149705369-ed244982-1a86-41db-8aae-38b73d57485c.png">
<img width="504" alt="Screen Shot 2022-01-16 at 7 44 15 PM" src="https://user-images.githubusercontent.com/5726308/149705380-d20d306e-b643-4a46-b572-baf9c8a6c17b.png">

**Comment by hmarr** [comment]
I've also noticed this – it seems to have become worse with recent macOS upgrades, too.

Right now the stats are fetched by running the following tools every second:
- `ps` - this records the CPU and memory stats, and doesn't seem to cause significant overhead.
- `nettop` - this records the network IO stats, and does seem to cause more overhead. Additionally I've noticed it causing the security software my employer uses to consume a lot of CPU, I think because it seems to do a lot of work when the process starts up (loading dynamic libraries, etc).

I see a few paths forward:
1. As you suggested, provide a way of toggling certain resources on or off.
2. Rather than running `ps` and `nettop` as a new process every interval, instead run longer-lived processes that emit output periodically (e.g. for nettop, use `-L 60` rather than `-L 1` to gather one minute's worth of samples per process). Forking fewer processes should somewhat reduce the load on the system, at the cost of complicating the code.
3. Finally, removing the extra stats altogether is an option. I personally very rarely use panes other than the CPU pane, so wouldn't mind much if we ditched memory and network stats.

What are your thoughts? I think option 2 would be ideal, but also probably the most work. If few people are using the non-CPU stats, option 3 is probably the best path forward, but I unfortunately don't have any data on that.

**Comment by hmarr** [comment]
I ended up adding a toggle for network monitoring in [v0.8](https://github.com/hmarr/vitals/releases/tag/v0.8). I also eliminated some unnecessary work (sorting the list of processes) when the pane is closed, which should reduce CPU usage a little.

From running v0.8 myself with network stats disabled, it seems like the energy usage is significantly lower. It's gone from hovering around 1.7 to 0.4 on my computer. I hope this does the trick for you too!
