### ISSUE TITLE
Vitals 0.8 keeps crashing

### ISSUE THREAD

**Issue by jmfbk** [hmarr/vitals#18]
I keep returning to my machine after a few hours to find Vitals not running. Crash log attached
[Vitals-2022-04-11-192349.txt](https://github.com/hmarr/vitals/files/8473124/Vitals-2022-04-11-192349.txt)
.

**Comment by hmarr** [comment]
Thanks for reporting this. I was able to track it down and reproduce it, and it should be fixed in v0.9 (available in my tap, and there's an [open PR](https://github.com/Homebrew/homebrew-cask/pull/121987) for the main homebrew repo).

Would you mind trying out v0.9 and verifying it fixes the issue? I'll close this out for now but feel free to reopen it if the problem reoccurs.

**Comment by jmfbk** [comment]
It's been running fine all morning. Ship it! [and thanks for the quick work!]

**Comment by hmarr** [comment]
That sounds promising! 🚀
